# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/map_reduce.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16proto/map_reduce.proto\x12\x0f\x62\x61\x63kup_protocol\x1a\x1bgoogle/protobuf/empty.proto\"\x1c\n\x0cNotification\x12\x0c\n\x04path\x18\x01 \x01(\t\"5\n\x08Response\x12)\n\x08response\x18\x01 \x01(\x0e\x32\x17.backup_protocol.Status*\x1f\n\x06Status\x12\x0b\n\x07SUCCESS\x10\x00\x12\x08\n\x04\x46\x41IL\x10\x01\x32\xd5\x01\n\x06Master\x12\x45\n\x0cStartReducer\x12\x1d.backup_protocol.Notification\x1a\x16.google.protobuf.Empty\x12\x44\n\x0bStartMapper\x12\x1d.backup_protocol.Notification\x1a\x16.google.protobuf.Empty\x12>\n\x0cNotifyMaster\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Emptyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.map_reduce_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STATUS._serialized_start=157
  _STATUS._serialized_end=188
  _NOTIFICATION._serialized_start=72
  _NOTIFICATION._serialized_end=100
  _RESPONSE._serialized_start=102
  _RESPONSE._serialized_end=155
  _MASTER._serialized_start=191
  _MASTER._serialized_end=404
# @@protoc_insertion_point(module_scope)
